# Generated by Django 3.1.4 on 2021-02-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('wall', '0002_auto_20210217_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneHomeworkNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField(auto_now=True)),
                ('homework_hash', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'done-homework-note',
                'verbose_name_plural': 'done-homework-notes',
            },
        ),
    ]
